// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Beginner-0]
	_ = x[Amateur-1]
	_ = x[Skilled-2]
	_ = x[Great-3]
	_ = x[Advanced-4]
	_ = x[Expert-5]
}

const _Rank_name = "BeginnerAmateurSkilledGreatAdvancedExpert"

var _Rank_index = [...]uint8{0, 8, 15, 22, 27, 35, 41}

func (i Rank) String() string {
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
